name: Update Stargazers Data

on:
  star:
    types: [created, deleted]
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: data

      - name: Fetch API Data
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p .github/data
          
          # Fetch all stargazers
          gh api --paginate "repos/${{ github.repository }}/stargazers" > .github/data/stargazers.json
          
          # Fetch total repo info
          gh api "repos/${{ github.repository }}" > .github/data/repo.json

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add .github/data/stargazers.json .github/data/repo.json
          
          git commit -m "chore: update stargazers data" || echo "No changes to commit"
          git push origin HEAD:data
